import { LoginView } from "views/login_view.slint";

export component AppWindow inherits Window {
    title: "Bodex v1.0 - Inicio de Sesión";
    width: 900px;
    height: 600px;
    background: #0a0a0f;

    in-out property current-view: "login";

    Rectangle {
        width: 100%;
        height: 100%;
        background: rgba(10, 10, 15, 0.9);
        border-radius: 8px;
        border-width: 1px;
        border-color: #00ffff;
    }
    
   }
